# ============================================================
#  SOC Platform - Shared Data Models
# ============================================================
import json
import time


class LogEvent:
    """
    A single log event sent from Agent → Manager.
    All communication uses this structure (serialized as JSON).
    """
    def __init__(self, agent_id, hostname, source, raw_log, timestamp=None):
        self.agent_id  = agent_id          # e.g. "agent-001"
        self.hostname  = hostname          # e.g. "lab-machine-1"
        self.source    = source            # e.g. "/var/log/auth.log"
        self.raw_log   = raw_log           # The actual log line string
        self.timestamp = timestamp or time.time()

    def to_json(self) -> str:
        return json.dumps(self.__dict__)

    @staticmethod
    def from_json(data: str) -> "LogEvent":
        d = json.loads(data)
        return LogEvent(**d)

    def __repr__(self):
        return f"[{self.hostname}] [{self.source}] {self.raw_log[:80]}"


class Alert:
    """
    Generated by the Rule Engine when a LogEvent matches a rule.
    Stored in the database and shown on the Dashboard.
    """
    def __init__(self, rule_id, rule_name, severity, agent_id,
                 hostname, matched_log, timestamp=None):
        self.rule_id     = rule_id          # e.g. "R001"
        self.rule_name   = rule_name        # e.g. "SSH Brute Force"
        self.severity    = severity         # "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
        self.agent_id    = agent_id
        self.hostname    = hostname
        self.matched_log = matched_log      # The raw log line that triggered this
        self.timestamp   = timestamp or time.time()

    def to_dict(self) -> dict:
        return self.__dict__

    def __repr__(self):
        return f"[ALERT][{self.severity}] {self.rule_name} on {self.hostname}"
